spring:
  flyway:
    baselineOnMigrate: true
    enabled: true
  jpa:
    open-in-view: false
    show-sql: true
  banner:
    location: banner.txt
  datasource:
    url: ${HOST_DB}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver